#!/usr/bin/env bash
set -euo pipefail

# R2 history AQI gap checker
# Checks observations, AQI levels, AQI band gaps, hourly alignment, duplicate AQI rows,
# and index manifest coverage from a local Dropbox R2 backup.

# ─────────────────────────────────────────────
# User settings
# ─────────────────────────────────────────────

BASE_DIR="/Users/mikehinford/Dropbox/Apps/github-uk-air-quality-networks/CIC-Test/R2_history_backup/history"

TIMESERIES_ID="354"
STATION_ID="1575"
POLLUTANT_CODE="pm25"

FROM_UTC="2026-04-25 00:00:00"
TO_UTC_EXCLUSIVE="2026-05-10 00:00:00"

FROM_DAY_UTC="2026-04-25"
TO_DAY_UTC="2026-05-10"

OUT_DIR="./r2_aqi_gap_check_${TIMESERIES_ID}_${POLLUTANT_CODE}_$(date +%Y%m%d_%H%M%S)"

# ─────────────────────────────────────────────
# Pre-flight checks
# ─────────────────────────────────────────────

if ! command -v duckdb >/dev/null 2>&1; then
  echo "ERROR: duckdb command not found."
  echo "Install it first, or add it to PATH."
  exit 1
fi

if [ ! -d "$BASE_DIR" ]; then
  echo "ERROR: BASE_DIR does not exist:"
  echo "$BASE_DIR"
  exit 1
fi

mkdir -p "$OUT_DIR"

SQL_FILE="$OUT_DIR/check_r2_aqi_gaps.sql"
LOG_FILE="$OUT_DIR/run.log"

echo "Writing output to: $OUT_DIR"

# ─────────────────────────────────────────────
# Generate DuckDB SQL
# ─────────────────────────────────────────────

cat > "$SQL_FILE" <<SQL
.timer on

-- DuckDB R2 history AQI gap checker
-- Generated by check_r2_aqi_gaps.sh

create or replace temp view check_params as
select
  ${TIMESERIES_ID}::bigint as target_timeseries_id,
  ${STATION_ID}::bigint as target_station_id,
  '${POLLUTANT_CODE}'::varchar as target_pollutant_code,
  timestamp '${FROM_UTC}' as from_utc,
  timestamp '${TO_UTC_EXCLUSIVE}' as to_utc_exclusive,
  date '${FROM_DAY_UTC}' as from_day_utc,
  date '${TO_DAY_UTC}' as to_day_utc;

-- ─────────────────────────────────────────────
-- Load observations
-- ─────────────────────────────────────────────

create or replace temp view observations_all as
select
  observed_at as period_start_utc,
  timeseries_id,
  value as observation_value,
  connector_id,
  day_utc,
  filename
from read_parquet(
  [
    '${BASE_DIR}/v1/observations/day_utc=2026-05-*/connector_id=*/*.parquet',
    '${BASE_DIR}/v1/observations/day_utc=2026-04-*/connector_id=*/*.parquet'
  ],
  hive_partitioning = true,
  union_by_name = true,
  filename = true
);

create or replace temp view observations_range as
select o.*
from observations_all o
cross join check_params p
where o.period_start_utc >= p.from_utc
  and o.period_start_utc <  p.to_utc_exclusive
  and o.timeseries_id = p.target_timeseries_id;

-- ─────────────────────────────────────────────
-- Load AQI levels
-- ─────────────────────────────────────────────

create or replace temp view aqilevels_all as
select
  timestamp_hour_utc as period_start_utc,
  timeseries_id,
  station_id,
  daqi_index_level,
  eaqi_index_level,
  connector_id,
  day_utc,
  pollutant_code,
  filename
from read_parquet(
  [
    '${BASE_DIR}/v1/aqilevels/day_utc=2026-05-*/connector_id=*/*.parquet',
    '${BASE_DIR}/v1/aqilevels/day_utc=2026-04-*/connector_id=*/*.parquet'
  ],
  hive_partitioning = true,
  union_by_name = true,
  filename = true
);

create or replace temp view aqilevels_range as
select a.*
from aqilevels_all a
cross join check_params p
where a.period_start_utc >= p.from_utc
  and a.period_start_utc <  p.to_utc_exclusive
  and a.timeseries_id = p.target_timeseries_id
  and a.station_id = p.target_station_id
  and a.pollutant_code = p.target_pollutant_code;

-- ─────────────────────────────────────────────
-- Expected hourly timeline
-- ─────────────────────────────────────────────

create or replace temp view expected_hours as
select
  hour_utc as period_start_utc
from check_params p,
generate_series(
  p.from_utc,
  p.to_utc_exclusive - interval 1 hour,
  interval 1 hour
) as t(hour_utc);

-- ─────────────────────────────────────────────
-- Hourly alignment
-- ─────────────────────────────────────────────

create or replace temp view hourly_alignment as
select
  h.period_start_utc,

  o.timeseries_id as obs_timeseries_id,
  o.observation_value,
  o.connector_id as obs_connector_id,
  o.filename as obs_filename,

  a.timeseries_id as aqi_timeseries_id,
  a.station_id as aqi_station_id,
  a.pollutant_code,
  a.daqi_index_level,
  a.eaqi_index_level,
  a.connector_id as aqi_connector_id,
  a.filename as aqi_filename,

  case when o.period_start_utc is not null then 1 else 0 end as has_observation,
  case when a.period_start_utc is not null then 1 else 0 end as has_aqi_row,
  case when a.daqi_index_level is not null then 1 else 0 end as has_daqi,
  case when a.eaqi_index_level is not null then 1 else 0 end as has_eaqi,

  case
    when o.period_start_utc is not null
     and a.period_start_utc is not null
     and a.daqi_index_level is not null
     and a.eaqi_index_level is not null
      then 'complete'
    when o.period_start_utc is not null
     and a.period_start_utc is null
      then 'observation_without_aqi_row'
    when o.period_start_utc is null
     and a.period_start_utc is not null
      then 'aqi_without_observation'
    when a.period_start_utc is not null
     and a.daqi_index_level is null
     and a.eaqi_index_level is null
      then 'aqi_row_missing_both_indexes'
    when a.period_start_utc is not null
     and a.daqi_index_level is null
      then 'aqi_row_missing_daqi'
    when a.period_start_utc is not null
     and a.eaqi_index_level is null
      then 'aqi_row_missing_eaqi'
    when o.period_start_utc is null
     and a.period_start_utc is null
      then 'no_observation_or_aqi'
    else 'other'
  end as status

from expected_hours h
left join observations_range o
  on o.period_start_utc = h.period_start_utc
left join aqilevels_range a
  on a.period_start_utc = h.period_start_utc;

-- ─────────────────────────────────────────────
-- Index manifests
-- ─────────────────────────────────────────────

create or replace temp view obs_index_manifests as
select *
from read_json_auto(
  [
    '${BASE_DIR}/_index/observations_timeseries/day_utc=2026-05-*/connector_id=*/*.json',
    '${BASE_DIR}/_index/observations_timeseries/day_utc=2026-04-*/connector_id=*/*.json'
  ],
  filename = true,
  union_by_name = true
);

create or replace temp view aqi_index_manifests as
select *
from read_json_auto(
  [
    '${BASE_DIR}/_index/aqilevels_timeseries/day_utc=2026-05-*/connector_id=*/*.json',
    '${BASE_DIR}/_index/aqilevels_timeseries/day_utc=2026-04-*/connector_id=*/*.json'
  ],
  filename = true,
  union_by_name = true
);

-- ─────────────────────────────────────────────
-- Output CSVs
-- ─────────────────────────────────────────────

copy (
  select
    'expected_hours' as check_type,
    count(*) as row_count,
    min(period_start_utc) as first_period_start_utc,
    max(period_start_utc) as last_period_start_utc
  from expected_hours

  union all

  select
    'observations_rows' as check_type,
    count(*) as row_count,
    min(period_start_utc) as first_period_start_utc,
    max(period_start_utc) as last_period_start_utc
  from observations_range

  union all

  select
    'aqilevels_rows' as check_type,
    count(*) as row_count,
    min(period_start_utc) as first_period_start_utc,
    max(period_start_utc) as last_period_start_utc
  from aqilevels_range

  union all

  select
    'aqilevels_with_daqi' as check_type,
    count(*) filter (where daqi_index_level is not null) as row_count,
    min(period_start_utc) filter (where daqi_index_level is not null) as first_period_start_utc,
    max(period_start_utc) filter (where daqi_index_level is not null) as last_period_start_utc
  from aqilevels_range

  union all

  select
    'aqilevels_with_eaqi' as check_type,
    count(*) filter (where eaqi_index_level is not null) as row_count,
    min(period_start_utc) filter (where eaqi_index_level is not null) as first_period_start_utc,
    max(period_start_utc) filter (where eaqi_index_level is not null) as last_period_start_utc
  from aqilevels_range
) to '${OUT_DIR}/01_summary.csv' with (header, delimiter ',');

copy (
  select *
  from hourly_alignment
  order by period_start_utc
) to '${OUT_DIR}/02_hourly_alignment_all.csv' with (header, delimiter ',');

copy (
  select *
  from hourly_alignment
  where status <> 'complete'
  order by period_start_utc
) to '${OUT_DIR}/03_hourly_alignment_gaps_only.csv' with (header, delimiter ',');

copy (
  with missing as (
    select
      period_start_utc,
      status
    from hourly_alignment
    where status <> 'complete'
  ),
  numbered as (
    select
      *,
      row_number() over (partition by status order by period_start_utc) as rn
    from missing
  ),
  grouped as (
    select
      *,
      period_start_utc - rn * interval 1 hour as gap_group
    from numbered
  )
  select
    status,
    min(period_start_utc) as gap_start_utc,
    max(period_start_utc) as gap_end_utc,
    count(*) as missing_hours
  from grouped
  group by status, gap_group
  order by gap_start_utc, status
) to '${OUT_DIR}/04_gap_ranges_all_statuses.csv' with (header, delimiter ',');

copy (
  with band_status as (
    select
      period_start_utc,
      'DAQI' as band,
      case when has_daqi = 1 then 'present' else 'missing' end as band_status
    from hourly_alignment

    union all

    select
      period_start_utc,
      'EAQI' as band,
      case when has_eaqi = 1 then 'present' else 'missing' end as band_status
    from hourly_alignment
  ),
  missing as (
    select *
    from band_status
    where band_status = 'missing'
  ),
  numbered as (
    select
      *,
      row_number() over (partition by band order by period_start_utc) as rn
    from missing
  ),
  grouped as (
    select
      *,
      period_start_utc - rn * interval 1 hour as gap_group
    from numbered
  )
  select
    band,
    min(period_start_utc) as gap_start_utc,
    max(period_start_utc) as gap_end_utc,
    count(*) as missing_hours
  from grouped
  group by band, gap_group
  order by gap_start_utc, band
) to '${OUT_DIR}/05_gap_ranges_daqi_eaqi.csv' with (header, delimiter ',');

copy (
  select
    cast(period_start_utc as date) as day_utc,
    count(*) as expected_hours,
    count(*) filter (where has_observation = 1) as hours_with_observation,
    count(*) filter (where has_aqi_row = 1) as hours_with_aqi_row,
    count(*) filter (where has_daqi = 1) as hours_with_daqi,
    count(*) filter (where has_eaqi = 1) as hours_with_eaqi,
    count(*) filter (where status <> 'complete') as incomplete_hours
  from hourly_alignment
  group by cast(period_start_utc as date)
  order by day_utc
) to '${OUT_DIR}/06_day_by_day_coverage.csv' with (header, delimiter ',');

copy (
  select
    period_start_utc,
    timeseries_id,
    station_id,
    pollutant_code,
    count(*) as rows,
    count(distinct daqi_index_level) as distinct_daqi_levels,
    count(distinct eaqi_index_level) as distinct_eaqi_levels,
    string_agg(distinct cast(daqi_index_level as varchar), ', ' order by cast(daqi_index_level as varchar)) as daqi_levels,
    string_agg(distinct cast(eaqi_index_level as varchar), ', ' order by cast(eaqi_index_level as varchar)) as eaqi_levels
  from aqilevels_range
  group by period_start_utc, timeseries_id, station_id, pollutant_code
  having count(*) > 1
  order by period_start_utc
) to '${OUT_DIR}/07_duplicate_aqi_rows.csv' with (header, delimiter ',');

copy (
  select
    pollutant_code,
    count(*) as aqi_rows,
    min(period_start_utc) as first_period_start_utc,
    max(period_start_utc) as last_period_start_utc,
    min(daqi_index_level) as min_daqi,
    max(daqi_index_level) as max_daqi,
    min(eaqi_index_level) as min_eaqi,
    max(eaqi_index_level) as max_eaqi,
    count(*) filter (where daqi_index_level is not null) as rows_with_daqi,
    count(*) filter (where eaqi_index_level is not null) as rows_with_eaqi,
    count(*) filter (where daqi_index_level is null) as rows_missing_daqi,
    count(*) filter (where eaqi_index_level is null) as rows_missing_eaqi
  from aqilevels_range
  group by pollutant_code
  order by pollutant_code
) to '${OUT_DIR}/08_aqi_by_pollutant.csv' with (header, delimiter ',');

copy (
  select
    'observations_index' as domain,
    count(*) as candidate_manifest_count,
    count(distinct day_utc) as days_found,
    count(distinct connector_id) as connectors_found,
    sum(source_row_count)::bigint as source_row_count,
    sum(indexed_file_count)::bigint as indexed_file_count,
    min(day_utc) as first_day_utc,
    max(day_utc) as last_day_utc
  from obs_index_manifests m
  cross join check_params p
  where m.day_utc >= p.from_day_utc
    and m.day_utc <= p.to_day_utc
    and p.target_timeseries_id between m.min_timeseries_id and m.max_timeseries_id

  union all

  select
    'aqilevels_index' as domain,
    count(*) as candidate_manifest_count,
    count(distinct day_utc) as days_found,
    count(distinct connector_id) as connectors_found,
    sum(source_row_count)::bigint as source_row_count,
    sum(indexed_file_count)::bigint as indexed_file_count,
    min(day_utc) as first_day_utc,
    max(day_utc) as last_day_utc
  from aqi_index_manifests m
  cross join check_params p
  where m.day_utc >= p.from_day_utc
    and m.day_utc <= p.to_day_utc
    and p.target_timeseries_id between m.min_timeseries_id and m.max_timeseries_id
) to '${OUT_DIR}/09_index_manifest_summary.csv' with (header, delimiter ',');

copy (
  select
    'observations_index' as domain,
    day_utc,
    connector_id,
    min_timeseries_id,
    max_timeseries_id,
    source_row_count,
    indexed_file_count,
    schema_version,
    filename
  from obs_index_manifests m
  cross join check_params p
  where m.day_utc >= p.from_day_utc
    and m.day_utc <= p.to_day_utc
    and p.target_timeseries_id between m.min_timeseries_id and m.max_timeseries_id

  union all

  select
    'aqilevels_index' as domain,
    day_utc,
    connector_id,
    min_timeseries_id,
    max_timeseries_id,
    source_row_count,
    indexed_file_count,
    schema_version,
    filename
  from aqi_index_manifests m
  cross join check_params p
  where m.day_utc >= p.from_day_utc
    and m.day_utc <= p.to_day_utc
    and p.target_timeseries_id between m.min_timeseries_id and m.max_timeseries_id

  order by domain, day_utc, connector_id
) to '${OUT_DIR}/10_index_manifest_candidates.csv' with (header, delimiter ',');

copy (
  select
    'observations' as domain,
    connector_id,
    day_utc,
    count(*) as rows,
    min(period_start_utc) as first_period_start_utc,
    max(period_start_utc) as last_period_start_utc,
    filename
  from observations_range
  group by connector_id, day_utc, filename

  union all

  select
    'aqilevels' as domain,
    connector_id,
    day_utc,
    count(*) as rows,
    min(period_start_utc) as first_period_start_utc,
    max(period_start_utc) as last_period_start_utc,
    filename
  from aqilevels_range
  group by connector_id, day_utc, filename

  order by domain, day_utc, connector_id, filename
) to '${OUT_DIR}/11_source_files_with_rows.csv' with (header, delimiter ',');

-- Human-readable console output

.print ''
.print '=== 01 Summary ==='
select * from read_csv_auto('${OUT_DIR}/01_summary.csv');

.print ''
.print '=== 04 Gap ranges, all statuses ==='
select * from read_csv_auto('${OUT_DIR}/04_gap_ranges_all_statuses.csv');

.print ''
.print '=== 05 Gap ranges, DAQI/EAQI ==='
select * from read_csv_auto('${OUT_DIR}/05_gap_ranges_daqi_eaqi.csv');

.print ''
.print '=== 06 Day by day coverage ==='
select * from read_csv_auto('${OUT_DIR}/06_day_by_day_coverage.csv');

.print ''
.print '=== 09 Index manifest summary ==='
select * from read_csv_auto('${OUT_DIR}/09_index_manifest_summary.csv');
SQL

# ─────────────────────────────────────────────
# Run DuckDB
# ─────────────────────────────────────────────

echo "Running DuckDB..."
duckdb < "$SQL_FILE" 2>&1 | tee "$LOG_FILE"

# ─────────────────────────────────────────────
# Final output list
# ─────────────────────────────────────────────

echo
echo "Done."
echo "Output folder:"
echo "$OUT_DIR"
echo
echo "Useful files:"
echo "  01_summary.csv"
echo "  03_hourly_alignment_gaps_only.csv"
echo "  04_gap_ranges_all_statuses.csv"
echo "  05_gap_ranges_daqi_eaqi.csv"
echo "  06_day_by_day_coverage.csv"
echo "  09_index_manifest_summary.csv"
echo "  11_source_files_with_rows.csv"
echo
echo "Full SQL:"
echo "  $SQL_FILE"
echo
echo "Run log:"
echo "  $LOG_FILE"